language: node_js
node_js:
  - "7"

branches:
  only:
  - master

script:
  - npm install
  - browserify -t brfs src/app.js -o dist/js/bundle.js

cache:
  directories:
    - "node_modules"

deploy:
  provider: pages
  edge:
    branch: v1.8.47
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  target-branch: gh-pages
  on:
    branch: master
